blog/urls.py
from django.urls import path 
from .feeds import LatestPostsFeed
from . import views
app_name = 'blog'

## write your code here 
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),

]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap

sitemaps = {
    'posts':PostSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


## creating a user models 
class PublishedManager(models.Manager):
    def get_querset(self):
        return super(PublishedManager,self).get_queryset().filter(status = 'published')

# Create your models here.
class Post(models.Model):
    STATUS_CHOICES =(
        ('draft','Draft'),
        ('published','published'),
    )
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 250, unique_for_date ='publish')
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default = 'draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    # creating a class meta
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[ self.publish.year, self.publish.month, self.publish.day, self.slug])
## creating a model for comments in this blog 
class Comment(models.Model):
    post =  models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comments')
    name = models.CharField(max_length = 80)
    email = models.EmailField()
    body = models. TextField()
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default= True)


    ### creating a Meta class 
    class Meta:
        ordering = ('created',)

    ## creating a function for displaying comments in the database by their author 
    def __str__(self):
        return f'Comment by{self.name} on {self.post}'

blog/forms.py
from django import forms 
from .models import Comment


## creating a class 
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length = 25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required = False,widget = forms.Textarea)

# creating a comment  Form by using the comment models 

class CommentForm(forms.ModelForm):
    ## creating a meta class 
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag

# Create your views here.
def post_list(request, tag_slug = None):
    posts = Post.published.all()
    tag = None 

    ##adding an if statements 
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        object_list =object_list.filter(tags__in=[tag])
    ## Adding pagination to the display page 
    object_list  = Post.published.all()
    paginator = Paginator (object_list,3) ## post in each page
    page = request.GET.get('page')

    #exceptiom 
    try:
        posts = paginator.page(page)
    

    except PageNotAnInteger:
        # if Page is not an integer deliver the  last page 
        posts = paginator.page(1)

    ## excepting an empty page 
    except EmptyPage:
        ## if the page is out of range then deliver the last page 
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{ 'page': page,'posts': posts,'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)

    # List of active comments for this Post 
    comments =post.comments.filter(active = True)
    new_comment = None 
    if request.method == 'POST':
        # A comment was posted 
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create a comment object But Don't save it into the database 
            new_comment = comment_form.save(commit = False)

            ## assign the current post to the comment current comment 
            new_comment.post = post 
            # save the comment into the database 
            new_comment.save()

    else:
        comment_form = CommentForm()
    return render(request,'blog/post/detail.html',{'post': post,'comments': comments,'new_comment': new_comment,'comment_form': comment_form})


#handling forms in a views 
def post_share(request, post_id):
    ## retrieve post by id 
    post = get_object_or_404(Post, id = post_id, status= 'published')
    sent = False

    # queryng
    if request.method  == "POST":
        # Form Was Submited 
        form = EmailPostForm(request.POST)

        if form.is_valid():
            #Form Fields Passed Validation 
            cd = form.cleaned_data
            post_url = request.build_absolute_url(post.get_absolute_url())
            subject = f"{cd['name']} Recommends you read ", f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n",f"{cd['name']}\'s  comments: {cd ['comments']}",
            sent_mail(subject, message, 'berringsdavid@mail.com', [cd['to']])
            sent = True


            # ...send Email 
    else:
        form = EmailPostForm()
    ##  adding some dictionaries 
    return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent': sent})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "blog.css" %}" rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body class = "m-5">
            <!-- Navigation bars.-->
          <nav class="navbar navbar-expand-lg navbar-light bg-white ">
            <a class="navbar-brand text-center" href="#">Berrings360</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Setting the real nav bar -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                                <li class="nav-item active">
                                          <a class="nav-link link-dark" href="{% url 'blog:post_list' %}">Home <span class="sr-only"></span></a>
                                </li>

                      </ul>

            </div>

          </nav>


          <div class="col-8">
            <div id="content">
              {% block content %}
              {% endblock %}
            </div>
             
          </div>
          <div class="col" id="sidebar">
              <div class="card bg-white mb-3 border-0">
                <div class="card-header">
                  <h2 class="fw-bolder fs-3 ">Other Post</h2>
                  <!-- Adding a subscription button -->
                  <p>
                    <a href = "{% url "blog:post_feed" %}">Subscribe My Feeds </a>
                  </p>
                  <h4>There are {% total_posts %} Total Post.</h4>
                  <h5><i>Latest Posts</i><h5>
                  {% show_latest_posts 3 %}
                </div>
                <!-- Most ommented Post -->
                <h3> Most Commmented Post </h3>
                <!-- Fetch a function get_Most_commented_post-->
                {% get_most_commented_posts as most_commented_posts %}
                <ul class="list-group list-group-flush">
                  {% for post in most_commented_posts %}
                  <li class="list-group-item">

                    <a href="{{ post.get_absolute_url}}" style="text-decoration:none;">{{ post.title}}</a>
                  </li>
                  {% endfor %}
                </ul>
            
            </div>
          </div>
    
              


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
    {{ post.body|markdown }}

    <!-- adding a url that dirrect the use to the share post page -->
    <p>
        <button type="button" class="btn btn-primary btn-lg">
            <a style="text-decoration: none; color: rgb(252, 247, 247);" href="{% url 'blog:post_share' post.id %}">
                Share Post 
            </a>
        </button>
    </p>

    <!-- Display the mumber of comments -->
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}


    <!-- Display the list of comments -->
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment{{ forloop.counter }} by {{ comment.name}}
                {{ comment.created}}

            </p>
            {{ comment.body | linebreaks}}
        </div>
        {% empty%}
            <p>Be the fast one to comment </p>
    {% endfor %}


    <!-- Display a form for users to add a new comment-->
    {% if new_comment %}
        <h2> Your comment have been added </h2>
    {% else %}
        <h2> Add a new  comment </h2>

        <!-- Creating a form for adding a new comment-->
        <form method = "post">
            {{ comment_form.as_p}}
            {% csrf_token %}
            <p><input type = "submit" value = "Add Comment"></p>

        </form>
    {% endif %}

{% endblock  %}

blog/templates/blog/post/latest_posts.html
<ol>
    {% for post in latest_posts %}
        <li >
            <a style="text-decoration: none;" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
    </ol>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %} Blog{% endblock %}

{% block content %}
<h1>My Articles </h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a class = "text"href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}     
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock  %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>

        {% else %}
            <h1>Share "{{ post.title }}" by e-mail</h1>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Send e-mail">

            </form>
            
    
    {% endif %}

{% endblock  %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>